---
abstract: unknown
author:
  - 'George Tsafas <elb0w@elbowrage.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mailgun
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA1: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
version: 0.4
